services:
  rag-chatbot:
    build:
      context: ./app
      shm_size: "16gb"
    ports:
      - target: 5050
        published: 5050 # MacOS AirPlay uses port 5000
        protocol: tcp
        mode: ingress
    environment:
      ASK_TOKEN: asktoken
      FLASK_APP: app.py
      SECRET_KEY: supersecret
      SEGMENT_WRITE_KEY: ${SEGMENT_WRITE_KEY} # Set your Segment write key here or in the .env file
      SESSION_COOKIE_SECURE: 0
      OPENAI_API_KEY: ${OPENAI_API_KEY} # Set your OpenAI API key here or in the .env file
      SENTENCE_TRANSFORMERS_HOME: /app/sentence-transformers
    volumes:
      - type: bind
        source: ./app
        target: /app
    command: flask run --host=0.0.0.0 --port=5050
    deploy:
      resources:
        reservations:
          memory: 4G

  bedrock:
    extends:
      file: compose.yaml
      service: bedrock
    environment:
      - AWS_REGION=us-west-2
      - AWS_PROFILE=defang-lab
    volumes:
      - type: bind
        source: ~/.aws
        target: /root/.aws