services:
  rag-chatbot:
    build:
      context: ./app
      shm_size: "16gb"
    ports:
      - target: 5000
        published: 5001 # MacOS AirPlay uses port 5000
        protocol: tcp
        mode: ingress
    environment:
      FLASK_APP: app.py
      SECRET_KEY: supersecret
      SEGMENT_WRITE_KEY: ${SEGMENT_WRITE_KEY} # Set your Segment write key here or in the .env file
      SESSION_COOKIE_SECURE: 0
      OPENAI_API_KEY: ${OPENAI_API_KEY} # Set your OpenAI API key here or in the .env file
    command: flask run --host=0.0.0.0
    deploy:
      resources:
        reservations:
          memory: 4G
