services:
  app:
    extends:
      file: compose.yaml
      service: app
    environment:
      ASK_TOKEN: asktoken
      FLASK_APP: app.py
      SECRET_KEY: supersecret
      SEGMENT_WRITE_KEY: ${SEGMENT_WRITE_KEY} # Set your Segment write key here or in the .env file
      SESSION_COOKIE_SECURE: 0
      OPENAI_API_KEY: ${OPENAI_API_KEY} # Set your OpenAI API key here or in the .env file
      OPENAI_BASE_URL: "http://llm:5051/api/v1"
      SENTENCE_TRANSFORMERS_HOME: /app/sentence-transformers
    volumes:
      - type: bind
        source: ./app
        target: /app
    command: flask run --host=0.0.0.0 --port=5050

  llm:
    extends:
      file: compose.yaml
      service: llm
    ports:
      - target: 5051
        published: 5051
        protocol: tcp
        mode: ingress
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWS_REGION=us-west-2
      - AWS_PROFILE=defang-lab
      - API_ROUTE_PREFIX=/api/v1
      - PORT=5051
    volumes:
      - type: bind
        source: ~/.aws
        target: /root/.aws
