name: Build
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout Repo
        uses: actions/checkout@v4

      # Add Python and Ruff linting steps
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Ruff
        run: pip install ruff>=0.12.5
      
      - name: Run Ruff linter
        working-directory: ./app
        run: ruff check .
      
      - name: Run Ruff formatter check
        working-directory: ./app
        run: ruff format --check .

      - name: Build Docker image
        working-directory: ./app
        run: |
          docker buildx build \
            --platform linux/amd64 \
            .
