name: Build
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout Repo
        uses: actions/checkout@v4

      # Ruff linting steps
      - name: Run Ruff linter
        uses: astral-sh/ruff-action@v1
        with:
          args: check ./app

      - name: Run Ruff formatter check
        uses: astral-sh/ruff-action@v1
        with:
          args: "format --check"

      - name: Build Docker image
        working-directory: ./app
        run: |
          docker buildx build \
            --platform linux/amd64 \
            .
